language: rust

matrix:
  include:
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu BUILD_MODE=docker
  ## currently unreproducible
  #- os: linux
  #  rust: stable
  #  env: TARGET=x86_64-unknown-linux-gnu BUILD_MODE=reprotest
  #- os: linux
  #  rust: stable
  #  env: TARGET=aarch64-unknown-linux-gnu
  #- os: linux
  #  rust: stable
  #  env: TARGET=i686-unknown-linux-gnu

install:
- sudo ci/travis_setup.sh
script:
- ci/test.sh
