snail(7)

# NAME

snail - parasitic network manager

# DESCRIPTION

The snail network manager configures dhcp on an interface and tests for working network conectivity. If a captive portal has been detected, the settings pushed by dhcp are provided to a scripting engine that can try to submit its forms. These settings can also be queried by *snailctl*.

# SCRIPTING

TODO

# ENGINE

TODO

# SEE ALSO

*snaild*(8), *snailctl*(8)
